# Generated by Django 2.0.7 on 2020-06-12 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_productshree_featured'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productshree',
            name='featured',
            field=models.BooleanField(default=True),
        ),
    ]
